### ISSUE TITLE
Offline messages are not sent

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#215]
1.write a message to an offline contact
2. send the message
3. contacts comes online
4. messages aren't sent
5. conversation continues
6. message aren't sent

**Comment by subliun** [comment]
I went cherry picking and I'm pretty sure this is fixed. https://github.com/subliun/Antox/commit/ec1b669553ff306a211e60676fda4fa93e9dec96

**Comment by agilob** [comment]
there was no update in froid repo or I still can reproduce it today.

**Comment by subliun** [comment]
was there an update today? it might not have come through yet

**Comment by agilob** [comment]
Ok, that's fixed but I lost contact names and they don't want to update even after being online for several minutes I still see hex instead contact name :<

**Comment by subliun** [comment]
I never really tested those typesafty changes huh

**Comment by toxtox** [comment]
Thanks for fixing it! I already described this bug in my comment for #107 ("Offline Messaging is Unreliable"). Maybe this issue ("Pre-Av-milestone") could be closed, too.

**Comment by subliun** [comment]
@agilob that's the second bug that I've fixed in my audio branch and forgotten to merge into master. I need to either stop doing that or give up on bug fixing until I've finished av.

**Comment by agilob** [comment]
Do AV ASAP, (unless more ppl report it) avatars works, so I can temporary live with that.

**Comment by cebe** [comment]
> Ok, that's fixed but I lost contact names and they don't want to update even after being online for several minutes I still see hex instead contact name :<

same here but also happy to wait for AV :)

**Comment by toxtox** [comment]
> Ok, that's fixed but I lost contact names and they don't want to update even after being online for several minutes I still see hex instead contact name :<

By the way, I **cannot** confirm agilob's bug report that the **contact names** are replaced by the hex (tox-id). I  Updated from build 0.23.133 to 0.23.160. Before I updated, I logged out and closed Antox, then I updated via f-droid. After starting the new Antox-build my "contacts names" were shown correctly.

**Comment by subliun** [comment]
too bad @agilob, I fixed the names and notifications. I just couldn't help myself.

**Comment by svalo** [comment]
I updated antox to 0.23.160 without logging out  nor closing it and now I see some contact with their toxid instead of their names. 
Strange thing is I see most of my contacts showing their tox id and just one (my laptop on which I updated qtox ~2 day ago) with nickname.

**Comment by svalo** [comment]
@subliun wow didn't have the time to comment and it's already fixed great! :+1:

**Comment by subliun** [comment]
Hehe.  :)

Thanks for reporting your experience though. It's great to have a team of testers looking out for issues.
