### ISSUE TITLE
Antox crashes when I want to create new profile

### ISSUE THREAD

**Issue by cebe** [subliun/Antox#48]
1. installed version 0.22 built at 5th May 2015 from fdroid
2. start the app
3. enter the name for new profile: "cebe"
4. Antox crashes/exists.

Fairphone FP1, Android 4.2.2

Is there a log I could provide or some other information?

**Comment by subliun** [comment]
Sigh. Looks like another issue with libkaliumjni. Register incognito should work. Thanks for reporting this, I'll have it fixed asap.

**Comment by subliun** [comment]
This should be fixed now.

**Comment by cebe** [comment]
awesome, when will this be available on Fdroid?

**Comment by subliun** [comment]
It was actually a toxme issue. Toxme was down the other day which was causing Antox to crash. If it still crashes it might be something else, but it started working for me yesterday so hopefully that was the issue. Of course Antox shouldn't crash when toxme is down, but that 's a separate fix which I will push sometime later today.

**Comment by cebe** [comment]
nope, the issue is not fixed. It crashes for me like it did when I reported the issue.

**Comment by cebe** [comment]
please reopen this, I will try to figure out more information about the crash.

**Comment by cebe** [comment]
Here is the error message from `adb logcat`:

```
E/AndroidRuntime(15932): FATAL EXCEPTION: main
E/AndroidRuntime(15932): java.lang.NullPointerException
E/AndroidRuntime(15932): 	at im.tox.antox.activities.LoginActivity.onItemSelected(LoginActivity.scala:58)
E/AndroidRuntime(15932): 	at android.widget.AdapterView.fireOnSelected(AdapterView.java:892)
E/AndroidRuntime(15932): 	at android.widget.AdapterView.selectionChanged(AdapterView.java:879)
E/AndroidRuntime(15932): 	at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1043)
E/AndroidRuntime(15932): 	at android.widget.AdapterView.handleDataChanged(AdapterView.java:1022)
E/AndroidRuntime(15932): 	at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:180)
E/AndroidRuntime(15932): 	at android.widget.Spinner.onMeasure(Spinner.java:439)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime(15932): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
E/AndroidRuntime(15932): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
E/AndroidRuntime(15932): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.widget.RelativeLayout.measureChild(RelativeLayout.java:666)
E/AndroidRuntime(15932): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime(15932): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(15932): 	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime(15932): 	at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime(15932): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime(15932): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
E/AndroidRuntime(15932): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
E/AndroidRuntime(15932): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime(15932): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(15932): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2191)
E/AndroidRuntime(15932): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime(15932): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2165)
E/AndroidRuntime(15932): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1249)
E/AndroidRuntime(15932): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1443)
E/AndroidRuntime(15932): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
E/AndroidRuntime(15932): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
E/AndroidRuntime(15932): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
E/AndroidRuntime(15932): 	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
E/AndroidRuntime(15932): 	at android.view.Choreographer.doFrame(Choreographer.java:548)
E/AndroidRuntime(15932): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
E/AndroidRuntime(15932): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(15932): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(15932): 	at android.os.Looper.loop(Looper.java:153)
E/AndroidRuntime(15932): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(15932): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15932): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(15932): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
E/AndroidRuntime(15932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(15932): 	at dalvik.system.NativeStart.main(Native Method)
```
